spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Yangself549_
    url: jdbc:mysql://yangself.cn:3306/leigod_utils?useUnicode=true&characterEncoding=utf8&useSSL=false&&roundRobinLoadBalance=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    hikari:
      connection-timeout: 10000
      max-lifetime: 18000000
      minimum-idle: 3
      connection-test-query: SELECT 1
      maximum-pool-size: 10


server:
  port: 10180

leigod:
  login: https://webapi.leigod.com/api/auth/login
  pause: https://webapi.leigod.com/api/user/pause
  recover: https://webapi.leigod.com/api/user/recover
  info: https://webapi.leigod.com/api/user/info
  logout: https://webapi.leigod.com/api/auth/logout