POST http://localhost:10180/leigod/login
Content-Type: application/json

{
  "username": "13661201241",
  "password": "523145794"
}

### 查看个人信息
POST https://webapi.leigod.com/api/user/info
Content-Type: application/json

{
  "account_token": "5q1MW0kyrnbw3N3VZwWfw6pVNkXiyVzYBh3KIXXXh8sVvB3kHt7KrKQSaRxtPok8",
  "lang": "zh_CN"
}

### 暂停时间
POST https://webapi.leigod.com/api/user/pause
Content-Type: application/json

{
  "account_token": "5q1MW0kyrnbw3N3VZwWfw6pVNkXiyVzYBh3KIXXXh8sVvB3kHt7KrKQSaRxtPok8",
  "lang": "zh_CN"
}

### 恢复时间
POST https://webapi.leigod.com/api/user/recover
Content-Type: application/json

{
  "account_token": "5q1MW0kyrnbw3N3VZwWfw6pVNkXiyVzYBh3KIXXXh8sVvB3kHt7KrKQSaRxtPok8",
  "lang": "zh_CN"
}

### 退出登陆
POST https://webapi.leigod.com/api/auth/logout
Content-Type: application/json

{
  "account_token": "5q1MW0kyrnbw3N3VZwWfw6pVNkXiyVzYBh3KIXXXh8sVvB3kHt7KrKQSaRxtPok8",
  "lang": "zh_CN"
}